export const typeLabels = {
  broadcast: 'Broadcast',
  send_one: 'Transfer',
  send_many: 'Multi-transfer',
  create_account: 'Creating an account',
  create_node: 'Creating a node',
  retrieve_funds: 'Retrieving funds',
  change_account_key: 'Changing the account key',
  change_node_key: 'Changingn the node key',
  set_account_status: 'Setting the account status',
  set_node_status: 'Setting the node status',
  unset_account_status: 'Clearing the account status',
  unset_node_status: 'Clearing the node status',
  log_account: 'Recording the account state',
  get_account: 'Receiving an account',
  get_log: 'Receiving a log',
  get_broadcast: 'Receiving broadcast',
  get_blocks: 'Receiving blocks',
  get_transaction: 'Receiving a transaction',
  get_vipkeys: 'Receiving VIP keys',
  get_signatures: 'Receiving signatures',
  get_block: 'Receiving a block',
  get_accounts: 'Receiving accounts',
  get_message_list: 'Receiving messages',
  get_message: 'Receiving message',
  get_fields: 'Receiving fields',
};

export const fieldLabels = {
  address: 'Address',
  amount: 'Amount',
  blockId: 'Block ID',
  blockIdFrom: 'From block',
  blockIdTo: 'To block',
  hash: 'Hash',
  message: 'Message',
  messageLength: 'Message length',
  messageId: 'Message ID',
  nodeId: 'Node ID',
  nodeMessageId: 'Node message ID',
  publicKey: 'Public key',
  recipient: 'Recipient',
  sender: 'Sender',
  accountStatus: 'Account status',
  nodeStatus: 'Node status',
  time: 'Time',
  transactionId: 'Transaction ID',
  type: 'Type',
  vipHash: 'VIP hash',
  wireCount: 'Recipients',
  wires: 'Recipients',
};
