@startuml
hide footbox

actor User  as user
participant Page as client
participant Plugin as plugin

== Initialization ==
client -> plugin: init(callback)

== Signing ==
user ->client: request tx
client -> plugin: addTransaction()
note right: id, data, hash
user -> plugin: confirm tx
client <- plugin: callback()
note right: id, data, hash,\nsignature
hnote over client : send tx\nto network
client->user: tx status
@enduml